language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: YuYvTWeGIZW3WeXtPiWLJlk8DNmsJOYW+tN9xLZjjEPZiu8GG8nkWYUXfnna3TDMMGaZ7RXAGx79q6IScfHm2GJw1zPPueeS7wMSjAtXd5GuCHDm1hUIh7sIvFDFO4bh2BYYlP3XLsfkzUtbLWMnhzHRYKLfBd1qb2MxRDjRbOdYrWLgS198nlTU2jIT8m/BWdN5NjwOGk45qE03wOswzWtu+rtiJZiIhaG2a+4ZjjPzBL9cAM1bjRh67w+n7MrTAMNp8XY827sX4bXQ6NSh0mLaYj+USPGIp/AHEaFyuyvbxUtWx+Klmyx+D2kx8viOVEbTau3XU7zd0yA/T+6bqPIijHJ7pCZEIZc6v5mgh2e7138aKwVIoJklTP711unfwpln/Qxhfqkv2BS1heq4nQH4GiN0JvL5oe6Vsl8YBtqyDA+OLpcRCBTFJ1X+ugEqRZuIQbkoT5/D3eQFPqE9f523yT4S4bccu5m/ck9no5VeJG7apg6SpV8zQIjFkwFy98ZF4pRhynteChWS0jqMwTC4lwZd5Z/rWWFMYdsMB1mlV6wlLUmn5Rhwwm8GtjfTYh0SbDKNLYiB+DHbCv+CELfB/0qYCc8V3ZAYjn4LRm3sxfi3bTMXOWxcaXWagTV1YqgVvNzyiM0Sh52jvnfUc7M2BE0yVIzK9Pmv2lWrd1k=
  app: webpalvelinohjelm-ratebeer
  on:
    repo: mynttih/WebPalvelinohjelmointi_ratebeer
env:
  global:
    secure: BEXlW5vS5GPMHzMir150J+vXgoAv91EP5t+eL+EeD0SxBZ2nf/Z2962yz5abN0IxEJQMWbZAsKkcNH1/ygbyc8W8ZTq65seqJ0EjIuH6ZJHFgPszMZl43XQSRWdYTLn6KdD/wN7XsMlmV/zgk7tLA4cT8gwb+S05Z+kbVOdLQ31htQHFMDmZaVZtejDW87SGVLqiTGsFpBlsp0kfKdonXCWoHWXLKiNzeLZ9ogczSkZPYdqY2VP4HA519ufTN63F95ICAI1PQGGWmDDq6W9BFYZTc5EXHz366ximxSezlkWASJk49CR5hih3ioSq3/jyexteRbql1pqrbNJUHQ8sxxv/bCk+ZZM+0BZrIEjbjAyUspKHyqurs5GGpZQFpFEbT01Wskyk8QPm3QYlSlezT8LLOJd8or0x+tnk++N1cb7/VxlvP4L6kdCeOSM5zL/3KMIMnnbCPWJ7NyVZm/wjffzKH3mxBferTsrTMwokcMIe21CFBhBd09q4DjAtUdVPeaiaVT21YH8lbGVIcuVCSAR7NjaMxnnQ82q8htWngAijGrVETBW8KZvS5kJchc/NL+XHPiE08UPQ+5/vA/Y5NXd4xK5+zKGe9LIxgkpQhP9KAy/e+bGWf7drNU8hKQj7h/bWl0PhRdXoTTL9oVrrOwLQ9OPZgwmdjS6hkxzh2Gg=
